/* AUTO-GENERATED by scripts/gen-fixtures.mjs from fixtures/data/*.jsonl — do not edit.
 * Committed so the app is self-contained when subtree-pushed to the Lovable repo. */
/* eslint-disable */

export const ventures = [
  {
    "anchor_id": "dcb4feb3-ba01-55bc-838f-6e64a07b14db",
    "anchor_type": "repo",
    "created_at": "2026-07-15T09:00:00+00:00",
    "market_tags": [
      "robotics",
      "ai"
    ],
    "name": "GraspLab",
    "one_liner": "Foundation models for robotic grasping",
    "quality_tier": "scored",
    "status": "interviewing",
    "summary_ai": "ETH spin-off shipping open-source grasping foundation models.",
    "updated_at": "2026-07-15T09:00:00+00:00",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555",
    "website_url": "https://grasplab.ch"
  },
  {
    "anchor_id": "hnp-voice-01",
    "anchor_type": "hackathon_project",
    "created_at": "2026-07-15T09:00:00+00:00",
    "market_tags": [
      "ai",
      "python",
      "voice",
      "whisper"
    ],
    "name": "VoiceLab",
    "one_liner": "Multilingual voice agents for field technicians.",
    "quality_tier": null,
    "status": "sourced",
    "summary_ai": "Hackathon-born multilingual voice agents for field technicians.",
    "updated_at": "2026-07-15T09:00:00+00:00",
    "venture_id": "43e3beb0-b86e-51a4-873b-b055f2c504f0",
    "website_url": "https://demo.hack-nation.ai/hnp-voice-01"
  }
];

export const ventureScores = [
  {
    "breakdown": {
      "categories": {
        "ideal_match": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Education 92, domain-fit 0.91, stars p95",
              "source_type": "fixture",
              "source_url": "https://grasplab.ch"
            }
          ],
          "method": "structured_match",
          "rationale": "Education 92, domain-fit 0.91, stars p95",
          "score": 84
        },
        "individual_experience": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "342 commits in 12mo on an 8,200-star repo",
              "source_type": "fixture",
              "source_url": "https://github.com/grasplab/grasp-anything"
            }
          ],
          "method": "sql_features",
          "rationale": "342 commits in 12mo on an 8,200-star repo",
          "score": 82
        },
        "market": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Robotic manipulation TAM growing with named competitors",
              "source_type": "fixture",
              "source_url": "https://example.com/market-report"
            }
          ],
          "method": "web_agent",
          "rationale": "Robotic manipulation TAM growing with named competitors",
          "score": 68
        },
        "network_ties": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "2-hop path to a funded founder via coauthor graph",
              "source_type": "fixture",
              "source_url": "https://api.openalex.org/works/W4400000001"
            }
          ],
          "method": "graph",
          "rationale": "2-hop path to a funded founder via coauthor graph",
          "score": 60
        },
        "prior_collaboration": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Fischer and Zhang share a paper and a repo across 4 months",
              "source_type": "fixture",
              "source_url": "https://github.com/grasplab/grasp-anything"
            }
          ],
          "method": "sql_overlap",
          "rationale": "Fischer and Zhang share a paper and a repo across 4 months",
          "score": 90
        },
        "problem_realness": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Recurring complaints about grasping reliability in warehouse automation",
              "source_type": "fixture",
              "source_url": "https://news.ycombinator.com/item?id=fixture"
            }
          ],
          "method": "web_agent",
          "rationale": "Recurring complaints about grasping reliability in warehouse automation",
          "score": 74
        },
        "product_defensibility": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Own foundation model, hard-tech stack, permissive license",
              "source_type": "fixture",
              "source_url": "https://github.com/grasplab/grasp-anything"
            }
          ],
          "method": "ai_query",
          "rationale": "Own foundation model, hard-tech stack, permissive license",
          "score": 80
        },
        "schools": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Max tier ETH Zurich (97) across known members",
              "source_type": "fixture",
              "source_url": "https://api.openalex.org/works/W4400000001"
            }
          ],
          "method": "deterministic",
          "rationale": "Max tier ETH Zurich (97) across known members",
          "score": 92
        },
        "traction": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "8,200 stars in 4 months; revenue unknown pending interview",
              "source_type": "fixture",
              "source_url": "https://github.com/grasplab/grasp-anything"
            }
          ],
          "method": "hybrid",
          "rationale": "8,200 stars in 4 months; revenue unknown pending interview",
          "score": 71
        }
      },
      "schema_version": 1
    },
    "confidence": 0.82,
    "final_score": 78.4,
    "ideal_match": 84,
    "is_latest": true,
    "model_version": "fixture-scorer-1",
    "profile_id": "aaaaaaaa-0000-4000-8000-000000000003",
    "s_individual_experience": 82,
    "s_market": 68,
    "s_network_ties": 60,
    "s_prior_collaboration": 90,
    "s_problem_realness": 74,
    "s_product_defensibility": 80,
    "s_schools": 92,
    "s_traction": 71,
    "score_id": "bbbbbbbb-0000-4000-8000-000000000001",
    "scored_at": "2026-07-15T09:00:00+00:00",
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555",
    "weights_id": "aaaaaaaa-0000-4000-8000-000000000002"
  },
  {
    "breakdown": {
      "categories": {
        "ideal_match": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Education 92, domain-fit 0.91, stars p95",
              "source_type": "fixture",
              "source_url": "https://grasplab.ch"
            }
          ],
          "method": "structured_match",
          "rationale": "Education 92, domain-fit 0.91, stars p95",
          "score": 84
        },
        "individual_experience": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "342 commits in 12mo on an 8,200-star repo",
              "source_type": "fixture",
              "source_url": "https://github.com/grasplab/grasp-anything"
            }
          ],
          "method": "sql_features",
          "rationale": "342 commits in 12mo on an 8,200-star repo",
          "score": 82
        },
        "market": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Robotic manipulation TAM growing with named competitors",
              "source_type": "fixture",
              "source_url": "https://example.com/market-report"
            }
          ],
          "method": "web_agent",
          "rationale": "Robotic manipulation TAM growing with named competitors",
          "score": 68
        },
        "network_ties": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "2-hop path to a funded founder via coauthor graph",
              "source_type": "fixture",
              "source_url": "https://api.openalex.org/works/W4400000001"
            }
          ],
          "method": "graph",
          "rationale": "2-hop path to a funded founder via coauthor graph",
          "score": 60
        },
        "prior_collaboration": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Fischer and Zhang share a paper and a repo across 4 months",
              "source_type": "fixture",
              "source_url": "https://github.com/grasplab/grasp-anything"
            }
          ],
          "method": "sql_overlap",
          "rationale": "Fischer and Zhang share a paper and a repo across 4 months",
          "score": 90
        },
        "problem_realness": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Recurring complaints about grasping reliability in warehouse automation",
              "source_type": "fixture",
              "source_url": "https://news.ycombinator.com/item?id=fixture"
            }
          ],
          "method": "web_agent",
          "rationale": "Recurring complaints about grasping reliability in warehouse automation",
          "score": 74
        },
        "product_defensibility": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Own foundation model, hard-tech stack, permissive license",
              "source_type": "fixture",
              "source_url": "https://github.com/grasplab/grasp-anything"
            }
          ],
          "method": "ai_query",
          "rationale": "Own foundation model, hard-tech stack, permissive license",
          "score": 80
        },
        "schools": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "Max tier ETH Zurich (97) across known members",
              "source_type": "fixture",
              "source_url": "https://api.openalex.org/works/W4400000001"
            }
          ],
          "method": "deterministic",
          "rationale": "Max tier ETH Zurich (97) across known members",
          "score": 92
        },
        "traction": {
          "confidence": 0.8,
          "evidence": [
            {
              "claim": "8,200 stars in 4 months; revenue unknown pending interview",
              "source_type": "fixture",
              "source_url": "https://github.com/grasplab/grasp-anything"
            }
          ],
          "method": "hybrid",
          "rationale": "8,200 stars in 4 months; revenue unknown pending interview",
          "score": 71
        }
      },
      "schema_version": 1
    },
    "confidence": 0.7,
    "final_score": 74.1,
    "ideal_match": 84,
    "is_latest": false,
    "model_version": "fixture-scorer-1",
    "profile_id": "aaaaaaaa-0000-4000-8000-000000000003",
    "s_individual_experience": 82,
    "s_market": 68,
    "s_network_ties": 60,
    "s_prior_collaboration": 90,
    "s_problem_realness": 74,
    "s_product_defensibility": 80,
    "s_schools": 92,
    "s_traction": 71,
    "score_id": "bbbbbbbb-0000-4000-8000-000000000002",
    "scored_at": "2026-07-12T09:00:00+00:00",
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555",
    "weights_id": "aaaaaaaa-0000-4000-8000-000000000002"
  },
  {
    "breakdown": {
      "categories": {
        "schools": {
          "confidence": 0.7,
          "evidence": [
            {
              "claim": "EPFL across both members",
              "source_type": "fixture",
              "source_url": "https://projects.hack-nation.ai/.netlify/functions/bff-public-people-v2?limit=5000"
            }
          ],
          "method": "deterministic",
          "rationale": "EPFL across both members",
          "score": 93
        },
        "traction": {
          "confidence": 0.5,
          "evidence": [
            {
              "claim": "HackNation 2026 Applied AI entry with a working on-device demo",
              "source_type": "fixture",
              "source_url": "https://demo.hack-nation.ai/hnp-voice-01"
            }
          ],
          "method": "hybrid",
          "rationale": "HackNation 2026 Applied AI entry with a working on-device demo",
          "score": 40
        }
      },
      "schema_version": 1
    },
    "confidence": 0.55,
    "final_score": 54.9,
    "ideal_match": 48,
    "is_latest": true,
    "model_version": "fixture-scorer-1",
    "profile_id": "aaaaaaaa-0000-4000-8000-000000000003",
    "s_individual_experience": 55,
    "s_market": 58,
    "s_network_ties": 30,
    "s_prior_collaboration": 45,
    "s_problem_realness": 70,
    "s_product_defensibility": 52,
    "s_schools": 93,
    "s_traction": 40,
    "score_id": "bbbbbbbb-0000-4000-8000-000000000007",
    "scored_at": "2026-07-15T09:00:00+00:00",
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "venture_id": "43e3beb0-b86e-51a4-873b-b055f2c504f0",
    "weights_id": "aaaaaaaa-0000-4000-8000-000000000002"
  }
];

export const ventureMembers = [
  {
    "added_at": "2026-07-15T09:00:00+00:00",
    "added_by": "pipeline",
    "evidence": {
      "contribution_share": 0.62,
      "officer_role": "founder"
    },
    "is_founder_guess": true,
    "person_id": "11111111-1111-4111-8111-000000000001",
    "role_hint": "founder",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555",
    "weight": 0.62
  },
  {
    "added_at": "2026-07-15T09:00:00+00:00",
    "added_by": "pipeline",
    "evidence": {
      "contribution_share": 0.38
    },
    "is_founder_guess": false,
    "person_id": "22222222-2222-4222-8222-000000000002",
    "role_hint": "maintainer",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555",
    "weight": 0.38
  },
  {
    "added_at": "2026-07-15T09:00:00+00:00",
    "added_by": "pipeline",
    "evidence": {
      "hacknation_role": "author"
    },
    "is_founder_guess": true,
    "person_id": "99999999-9999-4999-8999-000000000009",
    "role_hint": "founder",
    "venture_id": "43e3beb0-b86e-51a4-873b-b055f2c504f0",
    "weight": 0.5
  },
  {
    "added_at": "2026-07-15T09:00:00+00:00",
    "added_by": "pipeline",
    "evidence": {
      "hacknation_role": "ML engineer"
    },
    "is_founder_guess": false,
    "person_id": "88888888-8888-4888-8888-000000000008",
    "role_hint": "ML engineer",
    "venture_id": "43e3beb0-b86e-51a4-873b-b055f2c504f0",
    "weight": 0.5
  }
];

export const theses = [
  {
    "check_size_max_chf": 1000000,
    "check_size_min_chf": 250000,
    "exclude_corporate_oss": true,
    "geographies": [
      "CH",
      "EU"
    ],
    "is_active": true,
    "max_team": 6,
    "min_team": 1,
    "name": "Swiss deep-tech pre-seed",
    "notes": "Hardware-adjacent AI, researcher founders.",
    "owner_email": "partner@fund.example",
    "require_no_prior_vc": true,
    "sectors": [
      "robotics",
      "ai"
    ],
    "stages": [
      "pre-seed",
      "seed"
    ],
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "updated_at": "2026-07-15T09:00:00+00:00",
    "updated_by": "partner@fund.example"
  }
];

export const scoreWeights = [
  {
    "is_active": true,
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "updated_at": "2026-07-15T09:00:00+00:00",
    "updated_by": "partner@fund.example",
    "version": 1,
    "w_ideal_match": 0.1,
    "w_individual_experience": 0.15,
    "w_market": 0.1,
    "w_network_ties": 0.05,
    "w_prior_collaboration": 0.1,
    "w_problem_realness": 0.15,
    "w_product_defensibility": 0.15,
    "w_schools": 0.1,
    "w_traction": 0.1,
    "weights_id": "aaaaaaaa-0000-4000-8000-000000000002"
  }
];

export const outreach = [
  {
    "body": "We came across your repository grasp-anything and your paper GraspFM...",
    "channel": "email",
    "consent_at": "2026-07-16T10:00:00+00:00",
    "created_by": "partner@fund.example",
    "history": null,
    "last_event_at": "2026-07-16T10:00:00+00:00",
    "outreach_id": "bbbbbbbb-0000-4000-8000-000000000004",
    "person_id": "11111111-1111-4111-8111-000000000001",
    "question_plan": {
      "questions": [
        "Do you have paying pilots or revenue today?"
      ]
    },
    "sent_at": "2026-07-15T10:00:00+00:00",
    "status": "consented",
    "subject": "Your work on GraspFM",
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "to_email": "lena.fischer@ethz.ch",
    "token_expires_at": "2026-07-29T09:00:00+00:00",
    "token_hash": "5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456",
    "updated_at": "2026-07-15T09:00:00+00:00",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555"
  }
];

export const ventureGaps = [
  {
    "category": "traction",
    "created_at": "2026-07-15T09:00:00+00:00",
    "field": "traction.revenue",
    "importance": 0.9,
    "question_text": "Do you have paying pilots or revenue today?",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555"
  },
  {
    "category": "market",
    "created_at": "2026-07-15T09:00:00+00:00",
    "field": "market.tam",
    "importance": 0.7,
    "question_text": "Which customer segment do you serve first, and how large is it?",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555"
  }
];

export const interviews = [
  {
    "completed_at": "2026-07-16T10:19:00+00:00",
    "consent_confirmed": true,
    "extracted": {
      "career": [
        {
          "organization": "GraspLab AG",
          "role": "Founder",
          "start_year": 2026
        }
      ],
      "education": [
        {
          "degree": "PhD",
          "field": "Robotics",
          "institution": "ETH Zurich"
        }
      ],
      "funding_status": {
        "raised_before": false
      },
      "schema_version": 1,
      "team_commitment": {
        "status": "full_time"
      },
      "traction_claims": [
        {
          "as_of": "2026-07-16",
          "metric": "paid_pilots",
          "value": "3",
          "verified": false
        }
      ]
    },
    "interview_id": "bbbbbbbb-0000-4000-8000-000000000005",
    "model_version": "fixture-interview-1",
    "outreach_id": "bbbbbbbb-0000-4000-8000-000000000004",
    "person_id": "11111111-1111-4111-8111-000000000001",
    "rescore_score_id": "bbbbbbbb-0000-4000-8000-000000000001",
    "started_at": "2026-07-16T10:05:00+00:00",
    "transcript": [
      {
        "at": "2026-07-16T10:06:00+00:00",
        "role": "assistant",
        "text": "Thanks for consenting. Do you have paying pilots?"
      },
      {
        "at": "2026-07-16T10:07:00+00:00",
        "role": "founder",
        "text": "Three paid pilots with logistics companies."
      }
    ],
    "updated_at": "2026-07-15T09:00:00+00:00",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555"
  }
];

export const memos = [
  {
    "generated_at": "2026-07-15T09:00:00+00:00",
    "is_latest": true,
    "memo_id": "bbbbbbbb-0000-4000-8000-000000000003",
    "model_version": "fixture-memo-1",
    "run_id": "fixture-run-001",
    "sections": {
      "company_snapshot": {
        "bullets": [
          {
            "evidence": [
              {
                "claim": "GraspLab AG incorporated in Zurich on 2026-06-20.",
                "source_type": "fixture",
                "source_url": "https://www.zefix.admin.ch/api/v1/company/uid/CHE-123.456.789"
              }
            ],
            "text": "GraspLab AG incorporated in Zurich on 2026-06-20."
          }
        ]
      },
      "competition": {
        "bullets": [
          {
            "evidence": [
              {
                "claim": "Competes with in-house grasping stacks at large robotics vendors.",
                "source_type": "fixture",
                "source_url": "https://example.com/market-report"
              }
            ],
            "text": "Competes with in-house grasping stacks at large robotics vendors."
          }
        ]
      },
      "investment_hypotheses": {
        "bullets": [
          {
            "evidence": [
              {
                "claim": "Grasping foundation models are becoming the default robotics stack.",
                "source_type": "fixture",
                "source_url": "https://arxiv.org/abs/2506.11111"
              }
            ],
            "text": "Grasping foundation models are becoming the default robotics stack."
          }
        ]
      },
      "market_tam_sam_som": {
        "assumptions": [],
        "bullets": [
          {
            "gap_field": "market.tam",
            "missing": true,
            "text": "Bottom-up market sizing not yet computed."
          }
        ],
        "sam": null,
        "som": null,
        "tam": null
      },
      "problem_and_product": {
        "bullets": [
          {
            "evidence": [
              {
                "claim": "GraspFM targets unreliable grasping in warehouse automation.",
                "source_type": "fixture",
                "source_url": "https://arxiv.org/abs/2506.11111"
              }
            ],
            "text": "GraspFM targets unreliable grasping in warehouse automation."
          }
        ]
      },
      "schema_version": 1,
      "swot": {
        "bullets": [
          {
            "evidence": [
              {
                "claim": "Strength: 8,200-star open-source traction in 4 months.",
                "source_type": "fixture",
                "source_url": "https://github.com/grasplab/grasp-anything"
              }
            ],
            "text": "Strength: 8,200-star open-source traction in 4 months."
          }
        ]
      },
      "team_and_history": {
        "bullets": [
          {
            "evidence": [
              {
                "claim": "Founder Lena Fischer links GitHub, arXiv, and the Zefix registry.",
                "source_type": "fixture",
                "source_url": "https://api.openalex.org/works/W4400000001"
              }
            ],
            "text": "Founder Lena Fischer links GitHub, arXiv, and the Zefix registry."
          }
        ]
      },
      "technology_and_defensibility": {
        "bullets": [
          {
            "evidence": [
              {
                "claim": "Own foundation model with published research, not an API wrapper.",
                "source_type": "fixture",
                "source_url": "https://arxiv.org/abs/2506.11111"
              }
            ],
            "text": "Own foundation model with published research, not an API wrapper."
          }
        ]
      },
      "traction_and_kpis": {
        "bullets": [
          {
            "evidence": [
              {
                "claim": "8,200 GitHub stars, 410 forks.",
                "source_type": "fixture",
                "source_url": "https://github.com/grasplab/grasp-anything"
              }
            ],
            "text": "8,200 GitHub stars, 410 forks."
          },
          {
            "gap_field": "traction.revenue",
            "missing": true,
            "text": "Revenue and pilot count unknown."
          }
        ]
      }
    },
    "status": "draft",
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555"
  }
];

export const candidatePool = [
  {
    "exclusion_reasons": [],
    "funding_signal": "none_found",
    "included": true,
    "pool_built_at": "2026-07-15T09:00:00+00:00",
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "venture_id": "81963541-592e-5edf-8b82-9fe0b26b4555"
  },
  {
    "exclusion_reasons": [],
    "funding_signal": "none_found",
    "included": true,
    "pool_built_at": "2026-07-15T09:00:00+00:00",
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "venture_id": "43e3beb0-b86e-51a4-873b-b055f2c504f0"
  }
];

export const idealCandidates = [
  {
    "embedding_model": "fixture-fake-embedding",
    "is_active": true,
    "profile_id": "aaaaaaaa-0000-4000-8000-000000000003",
    "profile_json": {
      "education": [
        {
          "field": "robotics",
          "institution": "ETH Zurich",
          "level": "phd"
        }
      ],
      "feature_weights": {
        "recency_score": 0.5,
        "school_tier": 1,
        "stars_weighted": 1
      },
      "keywords": [
        "manipulation",
        "grasping",
        "foundation models"
      ],
      "narrative": "Robotics researcher-founder shipping open-source manipulation stacks.",
      "numeric_features": {
        "recency_score": 0.9,
        "school_tier": 0.95,
        "stars_weighted": 0.8
      },
      "schema_version": 1,
      "sectors": [
        "robotics"
      ]
    },
    "profile_text": "robotics manipulation grasping foundation models hardware founder open source",
    "thesis_id": "aaaaaaaa-0000-4000-8000-000000000001",
    "updated_at": "2026-07-15T09:00:00+00:00",
    "updated_by": "partner@fund.example",
    "version": 1
  }
];

export const persons = [
  {
    "affiliation": "ETH Zürich",
    "avatar_url": "https://avatars.example.com/u/501001",
    "country_code": "CH",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": null,
    "data_quality_score": 0.9,
    "display_name": "Léna Fischer",
    "emails": [
      "lena.fischer@ethz.ch"
    ],
    "full_name": "Léna Fischer",
    "github_login": "lenafischer",
    "headline": "Robotics founder building grasping foundation models at GraspLab.",
    "linkedin_url": null,
    "location": "Zurich, Switzerland",
    "merged_into_person_id": null,
    "orcid": "0000-0002-1825-0097",
    "person_id": "11111111-1111-4111-8111-000000000001",
    "primary_email": "lena.fischer@ethz.ch",
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": "https://grasplab.ch"
  },
  {
    "affiliation": "ETH Zürich",
    "avatar_url": null,
    "country_code": "CH",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": null,
    "data_quality_score": 0.7,
    "display_name": "Wei Zhang",
    "emails": [],
    "full_name": "Wei Zhang",
    "github_login": "weizhang-robotics",
    "headline": "Robot learning researcher at ETH Zurich.",
    "linkedin_url": null,
    "location": null,
    "merged_into_person_id": null,
    "orcid": null,
    "person_id": "22222222-2222-4222-8222-000000000002",
    "primary_email": null,
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": null
  },
  {
    "affiliation": "National University of Singapore",
    "avatar_url": null,
    "country_code": "SG",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": null,
    "data_quality_score": 0.6,
    "display_name": "Wei Zhang",
    "emails": [],
    "full_name": "Wei Zhang",
    "github_login": null,
    "headline": "Database systems researcher in Singapore.",
    "linkedin_url": null,
    "location": null,
    "merged_into_person_id": null,
    "orcid": null,
    "person_id": "33333333-3333-4333-8333-000000000003",
    "primary_email": null,
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": null
  },
  {
    "affiliation": null,
    "avatar_url": null,
    "country_code": "DE",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": null,
    "data_quality_score": 0.7,
    "display_name": "Nils Berger",
    "emails": [
      "nils@berger.dev"
    ],
    "full_name": "Nils Berger",
    "github_login": "nilsberger",
    "headline": "Simulation engineer behind FastSim.",
    "linkedin_url": null,
    "location": "Munich",
    "merged_into_person_id": null,
    "orcid": null,
    "person_id": "44444444-4444-4444-8444-000000000004",
    "primary_email": "nils@berger.dev",
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": null
  },
  {
    "affiliation": "KTH Royal Institute of Technology",
    "avatar_url": null,
    "country_code": "SE",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": null,
    "data_quality_score": 0.6,
    "display_name": "Aisha Patel",
    "emails": [],
    "full_name": "Aisha Patel",
    "github_login": null,
    "headline": "SLAM researcher at KTH.",
    "linkedin_url": null,
    "location": null,
    "merged_into_person_id": null,
    "orcid": "0000-0001-5109-3700",
    "person_id": "55555555-5555-4555-8555-000000000005",
    "primary_email": null,
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": "https://aishapatel.se"
  },
  {
    "affiliation": null,
    "avatar_url": null,
    "country_code": "DE",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": null,
    "data_quality_score": 0.5,
    "display_name": "Jonas Keller",
    "emails": [],
    "full_name": "Jonas Keller",
    "github_login": "jonaskeller",
    "headline": "Software developer in Berlin.",
    "linkedin_url": null,
    "location": "Berlin",
    "merged_into_person_id": null,
    "orcid": null,
    "person_id": "66666666-6666-4666-8666-000000000006",
    "primary_email": null,
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": null
  },
  {
    "affiliation": "Keller Advisory GmbH",
    "avatar_url": null,
    "country_code": "CH",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": null,
    "data_quality_score": 0.5,
    "display_name": "Jonas Keller",
    "emails": [],
    "full_name": "Jonas Keller",
    "github_login": null,
    "headline": "Corporate advisor in Zug.",
    "linkedin_url": null,
    "location": "Zug",
    "merged_into_person_id": null,
    "orcid": null,
    "person_id": "77777777-7777-4777-8777-000000000007",
    "primary_email": null,
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": null
  },
  {
    "affiliation": "EPFL",
    "avatar_url": null,
    "country_code": "CH",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": null,
    "data_quality_score": 0.7,
    "display_name": "Mira Kovac",
    "emails": [],
    "full_name": "Mira Kovac",
    "github_login": "mirakovac",
    "headline": "Speech ML engineer building on-device voice agents.",
    "linkedin_url": "https://www.linkedin.com/in/mira-kovac/",
    "location": "Lausanne",
    "merged_into_person_id": null,
    "orcid": null,
    "person_id": "88888888-8888-4888-8888-000000000008",
    "primary_email": null,
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": null
  },
  {
    "affiliation": "EPFL",
    "avatar_url": null,
    "country_code": "CH",
    "created_at": "2026-07-15T09:00:00+00:00",
    "cv_url": "https://cdn.hack-nation.ai/cv/hn-noah-01.pdf",
    "data_quality_score": 0.5,
    "display_name": "Noah Brunner",
    "emails": [],
    "full_name": "Noah Brunner",
    "github_login": null,
    "headline": "Voice-agent builder for field service teams.",
    "linkedin_url": null,
    "location": "Lausanne, Switzerland",
    "merged_into_person_id": null,
    "orcid": null,
    "person_id": "99999999-9999-4999-8999-000000000009",
    "primary_email": null,
    "status": "active",
    "twitter_handle": null,
    "updated_at": "2026-07-15T09:00:00+00:00",
    "website_url": null
  }
];
