"""ROR-backed institution resolution: any observed spelling to its registered name.

The alias data lives in data/institutions/ror_seed.jsonl (CC0, generated by
tools/build_institutions.py from the ROR registry) - never hardcoded in code.
Canonical form is the ROR display name; unknown organisations pass through the
mechanical key unchanged.
"""

import json
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from typing import Final

from contracts.models import Json
from tools.norm import org_key

SEED_PATH: Final[Path] = (
    Path(__file__).resolve().parent.parent / "data" / "institutions" / "ror_seed.jsonl"
)


class SeedFormatError(ValueError):
    """Raised when a seed line does not match the expected record shape."""

    def __init__(self, line: str) -> None:
        """Quote the offending line."""
        super().__init__(f"malformed institution seed line: {line[:120]!r}")


@dataclass(frozen=True, slots=True)
class InstitutionRecord:
    """One ROR organisation: canonical name plus every known spelling."""

    ror_id: str
    name: str
    country: str | None
    types: tuple[str, ...]
    aliases: tuple[str, ...]


def _string_items(value: Json | None) -> tuple[str, ...]:
    if not isinstance(value, list):
        return ()
    return tuple(item for item in value if isinstance(item, str))


def _parse_record(line: str) -> InstitutionRecord:
    parsed: Json = json.loads(line)
    if not isinstance(parsed, dict):
        raise SeedFormatError(line)
    ror_id = parsed.get("ror_id")
    name = parsed.get("name")
    if not isinstance(ror_id, str) or not isinstance(name, str):
        raise SeedFormatError(line)
    country = parsed.get("country")
    return InstitutionRecord(
        ror_id=ror_id,
        name=name,
        country=country if isinstance(country, str) else None,
        types=_string_items(parsed.get("types")),
        aliases=_string_items(parsed.get("aliases")),
    )


@cache
def _lookup() -> dict[str, InstitutionRecord]:
    table: dict[str, InstitutionRecord] = {}
    for line in SEED_PATH.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        record = _parse_record(line)
        keys = {org_key(record.name), *(org_key(alias) for alias in record.aliases)}
        for key in keys:
            if key:
                table.setdefault(key, record)
    return table


def resolve(raw: str) -> InstitutionRecord | None:
    """Resolve an observed organisation spelling to its ROR record.

    Args:
        raw: Affiliation or organisation name as observed at a source.

    Returns:
        The matching record, or None for organisations outside the seed.
    """
    return _lookup().get(org_key(raw))


def org_norm(raw: str) -> str:
    """The PSR org_norm: canonical registered name when known, mechanical key otherwise.

    Args:
        raw: Affiliation or organisation name as observed at a source.

    Returns:
        org_key of the ROR display name when resolved, else org_key(raw).
    """
    record = resolve(raw)
    return org_key(record.name) if record is not None else org_key(raw)
